### ISSUE TITLE
Strips Comfort negative lux values

### ISSUE THREAD

**Issue by Cokeisit** [Thorarin/com.sensative#10]
Stips Comfort reports negative readings for high values. My highest value is 29712 and the lowest is -31584. I guess the lowest value I have recorded should represent 33951 lux. There are plenty of negative readings in between the min value and -1.
I have a couple of occurrences of -1 that probably represent a lux over 64000 since the Strips Comfort can report 0-64000 lux.

**Comment by BugHoarder** [comment]
Hi
I'm a tester at Sensative. I believe the issue you have reported is due to a bug in our initial release of Strips Comfort prototypes where lux values greater than 32 767 lux are reported as negative. We have since fixed the issue and can assure you that future releases won't have this problem.

Please contact our support channel and see if you can get the unit replaced:
https://sensativesupport.zendesk.com/hc/en-us/requests/new 
Since the unit effectively is a prototype meant for testing purposes you may not be entitled for replacement, however it never hurts to ask.

**Comment by Thorarin** [comment]
Hmm, that's inconvenient, especially since firmware upgrades are not supported (AFAIK). 
I can look into building in a workaround and convert to unsigned int values.

Anyway, that's some bright lights you have 😋

**Comment by Cokeisit** [comment]
I sure hope there are support since they are bought from webhallen.com. How could prototypes have ended up at their store?

They are packaged in real retail boxes.

I'll contact Sensative but you (if you work there) should probably contact Webhallen and recall the shipment.

**Comment by Cokeisit** [comment]
> Anyway, that's some bright lights you have 😋

My light is called the Sun :)

**Comment by BugHoarder** [comment]
> I sure hope there are support since they are bought from webhallen.com. How could prototypes have ended up at their store?

My mistake, it seems we did send a couple of hundred units to retailers intended as end-user products. Prototype units will always be specifically marked as such. Been on a study break the last few months so was not completely up to date. ;P

Contact us on support, we should be able to organize a replacement. Pardon the inconvenience...

**Comment by Cokeisit** [comment]
A big thanks to Sensative for replacing my sensors. The new ones only report positive values.

For me this is not an issue anymore.

**Comment by Thorarin** [comment]
This issue should be fixed in 2.0.1 beta even for old firmwares.
