### ISSUE TITLE
something missing in the strips

### ISSUE THREAD

**Issue by satbopper** [Thorarin/com.sensative#16]
why i do not see any values of humidity, heat alarm and water alarm in the strip
is this app still being developed
i have only the temp and lumen working in the strip
i am running the beta app en homey 2.0.1

**Comment by Thorarin** [comment]
Actually, I submitted a new beta earlier today. 

If you're seeing an ambient light measurement, I assume you bought a Strips Comfort. It's not really intended to measure humidity as well.
The reason it shows the capability is because the Strips Drip uses the same base hardware, and because of that Homey cannot tell which of these two devices you have.

I have some ideas to allow the user to make a choice during pairing, but haven't started development on that yet.

**Comment by efurdal** [comment]
> Actually, I submitted a new beta earlier today.
> 
> If you're seeing an ambient light measurement, I assume you bought a Strips Comfort. It's not really intended to measure humidity as well.
> The reason it shows the capability is because the Strips Drip uses the same base hardware, and because of that Homey cannot tell which of these two devices you have.
> 
> I have some ideas to allow the user to make a choice during pairing, but haven't started development on that yet.

This is not the case. I have the Drip sensor and humidty values does not show... only a "-". 

Only get values on LUMINANCE and TEMPERATURE. And have confirmed that the Water leak alarm works well.

**Comment by Thorarin** [comment]
I finally managed to get my sensor to work. After that, it only took a little patience (and some messing around with water near my computer 🙄) to figure out what was going on.

Version 2.1.2 of the app should fix this issue. After it is approved (fingers crossed 😁), you should also set the reporting period to some non-zero value in your device settings, if you haven't already done so. See https://github.com/Thorarin/com.sensative/wiki/Strips-Comfort-Drip-Troubleshooting#humidity-level-is-not-being-reported
