### ISSUE TITLE
With Version 2.01 my strips stopped working

### ISSUE THREAD

**Issue by steplein** [Thorarin/com.sensative#17]
Dear developer team, first of all thanks for the great effort made with this app! My strips (guard) doesnt report status changes anymore after upgrading to version 2.01. Newly added strips gets recognized by homey but I am unable the change parameters (timeout) and also state changes arent reported to homey by these strips. Strips that has been added with version 2.0 parameters can be changed (even if the are positioned side by side with the ones added with Version 2.01 the newly added strips can not change parameters). Another strange thing I realized is that strips added with version 2.01 have beside the contact alarm also a tamper alarm. Could you maybe fix this issue or offer version 2.0 for download again? Thanks in advance!

**Comment by Thorarin** [comment]
What happens exactly when you try to change parameters? You mention a timeout, but I'm unable to reproduce this. Note that parameters aren't actually set when you click the save button. You have to wake up the Strips with a magnet first. The old web interface used to prompt the user about that, but the Homey App for firmware 2.0 doesn't seem to.

Releasing 2.0.0 wouldn't do any good, because nothing has changed about the parameters for the Strips Guard in between 2.0.0 and 2.0.1. Most likely your older strips were created with a 1.0.x version, because 2.0.0 also had the tamper alarm capability listed 🙂 Unfortunately the tamper alarm doesn't seem to work reliably, so I may end up removing it again if I cannot fix it.

**Comment by steplein** [comment]
hey thanks for digging into this. attached you can find the message i do get. when i try to change parameters in the strips added with 2.0.1. with the one i added with 2.0 parameters could be changed without any problem (even i dont have to wake up). i actually have three strips coming from the same box, so it is not very probable that these are different versions. so the change must somehow relate to the different app version. attached please find the screenshots from the one added with 2.0 and the other added with 2.0.1. if you need further information please let me know. thanks in advance. stephan

**Comment by steplein** [comment]
one additional remark i forgot. havent used 1.x of the app. this is a new homey delivered with homey version 2.0. so as far as i know a version of the app with 1.x was never installed (and might not even work). really strange. best. stephan


Anfang der weitergeleiteten Nachricht:

**Comment by Thorarin** [comment]
@steplein Did you ever get this to work? You could try using version 2.1.0 of the app, which is currently in test.
