### ISSUE TITLE
read luminance value

### ISSUE THREAD

**Issue by thob** [Thorarin/com.sensative#30]
is it possible to use the luminance value as a trigger - for instance - to turn on the light?

**Comment by Thorarin** [comment]
Yes, this is a built-in functionality of Homey.

1. Add card to the "When..." section of a new flow
2. Select the Strips Comfort device
3. Select "The luminance changed"

**However**, Strips Comfort  is pretty lazy in reporting changes in luminance. You will be able to improve this by setting the "High ambient light report level" and "Low ambient light report level" to values in the neighborhood of your tipping point where you want the lights to turn on or off.

Therefore, if you have a single trigger value for luminance, you may be able to get a satisfactory result. Otherwise, Strips may not be the best device for you. Personally I use a Fibaro Motion Sensor for exactly this purpose.

**Comment by thob** [comment]
hmm, thanks … I want to trigger an activity for particular value say 1000 how would I set this in the card I only get the "The luminance changed" - do you know what I mean?

**Comment by dirkg173** [comment]
You have to add a Logic card in the And... section, e.g. „greater than“ or „less than“ and choose the Lux tag.
